deployment:
  tasks:
    - export DEPLOYPATH=/home/c2675260c/pengme-backend
    - echo "🚀 Déploiement PengMe (main) ..."
    - cd $DEPLOYPATH
    - /opt/alt/php83/usr/bin/php artisan down || true
    - composer install --no-dev --optimize-autoloader
    - /opt/alt/php83/usr/bin/php artisan migrate --force
    - /opt/alt/php83/usr/bin/php artisan storage:link || true
    - chmod -R 775 storage bootstrap/cache
    - /opt/alt/php83/usr/bin/php artisan config:cache
    - /opt/alt/php83/usr/bin/php artisan route:cache
    - /opt/alt/php83/usr/bin/php artisan view:cache
    - /opt/alt/php83/usr/bin/php artisan optimize
    - /opt/alt/php83/usr/bin/php artisan up
    - echo "✅ Déploiement terminé avec succès !"
